# Generated by Django 5.1.2 on 2024-10-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_immobile_rename_cliente_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='immobile',
            options={'ordering': ['-id'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
    ]
