# Generated by Django 5.1.2 on 2024-10-09 01:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_immobile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmobileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imgs', verbose_name='Images')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobile_images', to='core.immobile')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Início')),
                ('date_end', models.DateTimeField(verbose_name='Fim')),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_location', to='core.immobile')),
            ],
            options={
                'verbose_name': 'Registrar Locação',
                'verbose_name_plural': 'Registrar Locação',
                'ordering': ['-id'],
            },
        ),
    ]
