# Generated by Django 5.1.2 on 2024-10-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_immobileimages_registerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlocation',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_location', to='core.immobile'),
        ),
    ]
